AngelFP/Wake-T

- README.md
Quick PR to reflect the fact that `Wake-T` is now on PyPI.
The README.md includes now the PyPI badge, and the installation instructions have been updated to show how to perform the installation with `pip`.
> Add PyPI badge and update installation instructions

- requirements.txt
This updated the `requirements.txt` slightly to use [semantic versioning](https://www.python.org/dev/peps/pep-0440/#compatible-release) ([SO](https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean)).
Follow-up to #12
openPMD-api follows [semantic versioning](https://semver.org/), thus APIs are guaranteed to be compatible for those changes:
- `0.Y.A` -> `0.Y.B`
- `X.A.*` -> `X.B.*`
- `<any>.<any>.*` -> `<any>.<any>.*`
In reality, our APIs expose breaking changes even less often and would often not even affect Wake-T (e.g. we also release a C++ API that is covered under the same SemVer). Nonetheless, I have some ideas on my backlog that I want to improve in the Python API, a few of them would introduce breakage (e.g. …
> requirements.txt: openPMD-api semver

- wake_t/diagnostics/openpmd_diag.py
Since the `cylindrical` geometry is not yet properly defined in the current version of the openPMD standard, the fields are now declared as having `thetaMode` geometry with only one mode. This is effectively the same, but it requires adding an extra axis to the fields which contains the available modes (only one in this case). Changing to this geometry allows for the use of tools such as openPMD-viewer (see https://github.com/openPMD/openPMD-viewer/pull/305) or VisualPIC for data analysis and visualization.
> Change geometry of fields to thetaMode in openPMD output

- wake_t/beamline_elements.py
Example:
```py
n_plasma = 1.e24
decay_length = 1.e-3
total_length = 5.e-3
def dens_func(z):
return n_plasma / np.square(1 + z / decay_length)
downramp = PlasmaRamp(total_length, profile=dens_func)
bunch_list = downramp.track(bunch)
```
> the user can pass a function for the plasma density ramp profile

- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/solver.py
This PR contains several improvements to the quasistatic wakefield model. It greatly improves the stability, specially for strongly non-linear wakes where a sharp blowout peak is present. It also allows for plasma columns of finite width, different from that of the simulation box.
* Plasma column can have a different radial extent than simulation box.
* Set `edge_order=2` when calculating `nabla_a2`.
* Implement new method for computing psi and derivatives at plasma particles. It is now done by interpolating between neighboring values. This ensures that `dr_psi=0` in a uniform plasma. The boundary conditions have also been reformulated. They are now more robust and allow for plasma columns of finite width.
* The minimum value of `psi` is now limited to -0.9. Also, the amplitude of dxi_psi …
> Improvements to quasistatic model

- wake_t/__init__.py
- wake_t/physics_models/laser/laser_pulse.py
This PR adds support for flattened Gaussian and Laguerre-Gauss pulses. The implementation is strongly based on FBPIC (thanks @RemiLehe, @MKirchen).
- Added new `LaserPulse` subclasses `LaguerreGaussPulse`, `FlattenedGaussianPulse` and `SummedPulse`.
- The `SummedPulse` class allows for combining several pulses into one. To simplify this, the `__add__` operator in `LaserPulse` has been overloaded to return a `SummedPulse`.
- Added a `cep_phase` argument to `GaussianPulse` to match the features of the new profiles.
- Changed the order of the `GaussianPulse` arguments to match that of the new profiles.
- The laser wavelength is now `l_0=0.8e-6` by default.
- Small changes in the format of docstrings.
- Added credits to FBPIC and authors.
> Add support for more laser pulse profiles

- wake_t/particles/deposition.py
- wake_t/physics_models/plasma_wakefields/qs_cold_fluid_1x3p.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/solver.py
The current way of calculating the azimuthal magnetic field had a problem where it did not take into account the whole charge of the beam, especially when the number of radial grid points along the bunch was small.
This PR fixes this issue as well as other related problems. These include:
* Correct calculation of `b_theta`.
* The use of Ruyten shapes for charge deposition has been reactivated and added as option.
* Several bug fixes in the implementation of the Ruyten shapes.
* The deposition methods now force all the charge to be deposited within the grid boundaries. This avoids having less charge in the edges of the grid, particularly when using `'cubic'` particle shapes.
* Fix small bug in the calculation of `z_max` in the deposition method.
> Correct calculation of beam space charge in Baxevanis solver

- wake_t/diagnostics/openpmd_diag.py
In some cases, when a `ParticleBunch` is created from external arrays, it can happen that this arrays are not contiguous. This only seems to be an issue when writing the openPMD diagnostics, which now will make sure the arrays are contiguous before adding them to the output.
> Make sure species arrays are contiguous

- wake_t/physics_models/laser/laser_pulse.py
This PR fixes an issue where, for the same `z_foc`, the laser would be initialized differently depending on how it was positioned in the comoving frame.
> Fix laser initialization

- wake_t/beamline_elements/plasma_stage.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
Modified the inclusion of the parabolic_coefficient in the qs_rz_baxevanis model (wakefield.py) to add a z-dependance. This follows the same format as the definition of the density profile n_p in the PlasmaStage module, ie plasma_stage._get_density_profile().
When a constant is passed, then the new function spits out an array of values like the z-array containing the constant at each element. When a function is passed, then the function is evaluated over the z-array and the result passed out as an array. 
The new wakefield.py model has been tested with a low intensity laser pulse in a plasma waveguide and compared to an independent code I wrote which models the propagation of the pulses in an arbitrary plasma density profile. 
For the tests, I tried both a plasma waveguide with a constant …
> adding z dependance to parabolic_coefficient

- wake_t/physics_models/plasma_wakefields/qs_cold_fluid_1x3p.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
The current names for the laser fields in the openPMD output are not very accurate. This PR renames the modulus of the complex laser envelope from `'a'` to `'a_mod'`, and the complex phase from `'aphi'` to `'a_phase'`.
> Rename laser output fields

- wake_t/beamline_elements/beamline.py
This PR fixes an issue in the `Beamline` element where the initial beam distribution would not be included in the openPMD diagnostics when `out_initial=True`.
> Fix bug in `Beamline` when using `out_initial=True`

- .github/workflows/publish-to-pypi.yml
Add a GitHub workflow to automatically generate and upload a Wake-T package to PyPI every time a new release is made (#60)
> Add workflow to publish to PyPI on release

- setup.cfg
- tests/test_bunch_read_save.py
- wake_t/__init__.py
- wake_t/utilities/bunch_generation.py
This PR changes the default behavior of the `get_from_file` method when reading from an openPMD file (#70):
* The `species_name` argument is no longer required when there is only one species in the file.
* When the `name` parameter is not specified (i.e., when the user does not want to give a new name to the `ParticleBunch` after reading it from file), the original name of the species will be maintained in the `ParticleBunch`.
> Improve default behavior of openPMD particle reader

- tests/test_active_plasma_lens.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/b_theta.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/deposition.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/plasma_push/ab5.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/plasma_push/rk4.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/psi_and_derivatives.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/solver.py
This PR rewrites the main loop that pushes the plasma column along the simulation box such that it can be fully compiled with numba. This speeds up the wakefield calculation by up to ~40-50%.
In order to compile this loop, the plasma particle pusher and plasma particle deposition have also been rewritten in a way that can be fully compiled with numba.
Due to the larger amount of numba functions, the initial compile time has also increased to about ~25 s. It would be good to look now into numba caching options (#35)
> Improve performance of Baxevanis wakefield model

- wake_t/fields/analytical_field.py
- wake_t/particles/deposition.py
- wake_t/particles/interpolation.py
- wake_t/particles/push/boris_pusher.py
- wake_t/particles/push/runge_kutta_4.py
- wake_t/physics_models/laser/envelope_solver.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/b_theta.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/deposition.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/plasma_push/ab5.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/plasma_push/rk4.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/psi_and_derivatives.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/solver.py
- wake_t/utilities/numba.py
This PR enables caching numba methods so that they do not need to be compiled every time the code is run. Similar to FBPIC, the caching can be disabled by setting the environment variable `WAKET_DISABLE_CACHING=1`.
Two custom `njit` decorators have been defined: `njit_serial` and `njit_parallel` (currently unused) to compile methods that should run in serial or that can run in parallel.
> Implement numba caching and custom decorators

- tests/test_custom_blowout.py
- tests/test_ramps.py
- tests/test_simple_blowout.py
- wake_t/diagnostics/openpmd_diag.py
- wake_t/particles/particle_bunch.py
- wake_t/physics_models/plasma_wakefields/qs_cold_fluid_1x3p.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
- wake_t/tracking/tracker.py
- Include all components of `E` and `B` (i.e., `r`, `t` and `z`) in the openPMD output, even if they are zero. This improves compatibility with post-processing tools such as the openPMD viewer.
- Set the correct units of the `B` field. Currently no units were set, as the diagnostics still expected the transverse wakefield `W` instead of `E` and `B`.
- In the `Tracker`, update the tracking time before updating the next object. This makes sure, for example, that the openPMD diagnostics have the correct updated time.
- In the `ParticleBunch`, use the current global time instead of `prop_distance` to calculate the `z` offset. This makes sure that the beam does not jitter in `z` in the openPMD diagnostics if the beam push and diagnostics do not occur at the same time.
In addition:
- Pass the …
> Improve openPMD diagnostics

- wake_t/particles/particle_bunch.py
Implements a simple strategy to track ballistically a bunch when its longitudinal position is smaller than `z_injection`: when this condition is true, the particles of the bunch are pushed normally, but with zero em fields. 
To activate this feature, the user just needs to define `z_injection` when initializing the `ParticleBunch`, e.g.:
`bunch = ParticleBunch(q, x, y, z, ux, uy, uz, z_injection=1e-3, name='bunch')`
> z injection

- wake_t/tracking/progress_bar.py
Fixes two issues with the new progress bar:
- The common clamping warnings (probably caused by rounding errors) are no longer displayed.
- The progress bar output is now directed to `sys.stdout`, as expected.
> Progress bar improvements

- tests/test_laser_envelope_model.py
- wake_t/beamline_elements/plasma_stage.py
- wake_t/physics_models/laser/envelope_solver.py
- wake_t/physics_models/laser/laser_pulse.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
This PR allows the laser envelope solver to have a different (smaller) time step than the wakefield update period defined by `dz_fields`. It defines a new parameter `laser_envelope_substeps` that can be given as input to a `PlasmaStage` when using the `quasistatic_2d` solver. This parameter must be an integer >= 1 (by default, 1) so that the time step of the envelope solver is `dz_fields / c / laser_envelope_substeps`.
In additon, this PR fixes two small bugs in the envelope solver that only become noticeable when the laser pulse reaches the back of the simulation box.
> Enable laser envelope solver subcycling

- wake_t/beamline_elements/plasma_stage.py
- wake_t/fields/rz_wakefield.py
- wake_t/physics_models/laser/laser_pulse.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
Implements a basic envelope solver sub-grid in z direction.
To enable, just pass `laser_envelope_subgrid` > 1 to the `PlasmaStage` object. 
It will sub-divide the grid used by the envelope solver by a factor `laser_envelope_subgrid`. 
The number of grid points in `z` of the envelope solver is then `nz * laser_envelope_subgrid`.
> Subgrid envelope

- README.md
The unit tests have been running on GitHub actions for quite a while now. This PR replaces the old Travis badge with the corresponding badge from GitHub actions.
> Replace old Travis badge with GitHub actions

- wake_t/beamline_elements/plasma_stage.py
- wake_t/fields/rz_wakefield.py
- wake_t/physics_models/laser/envelope_solver.py
- wake_t/physics_models/laser/laser_pulse.py
- wake_t/physics_models/plasma_wakefields/qs_cold_fluid_1x3p.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
New features:
- A new `laser_envelope_use_phase` parameter has been added. It controls whether the terms related to the longitudinal derivative of the complex envelope phase are taken into account in the laser envelope solver. This improves the stability of the solver in long simulations.
- An instance of `Field` is now accepted as a `wakefield_model` in any `PlasmaStage` class.
Bug fixes:
- Added missing `self` in `RZWakefield` class method.
> Make use of complex envelope phase optional + allow `Field` instances as `wakefield_model`

- tests/test_fluid_model.py
- tests/test_laser_envelope_model.py
- wake_t/physics_models/laser/envelope_solver.py
- wake_t/physics_models/laser/envelope_solver_non_centered.py
- wake_t/physics_models/laser/laser_pulse.py
- wake_t/physics_models/laser/tdma.py
This PR implements a non-centered version of the laser envelope solver that does not require the envelope at `t = t_n -dt`. The time discretization used results in the following equation:
This solver is particularly useful to compute the first time step of the envelope evolution. It provides a much better initialization than the previous method that greatly minimizes the numerical issues associated with it.
> Implement non centered envelope solver for laser initialization

- tests/test_active_plasma_lens.py
- tests/test_multibunch.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/b_theta.py
Allow for multiple iterations of this function. The a_0 or b_N calculated serves as the initial guess of a_0 or b_N for the next iteration. This way the correction factors K and U become small.
> Fix precision issue in calculate_ai_bi_from_axis and calculate_ai_bi_from_edge

- examples/track_plasma_fluid.py
- examples/track_plasma_qs2d.py
- tests/test_beamline.py
- tests/test_field_element.py
- wake_t/beamline_elements/__init__.py
- wake_t/beamline_elements/beamline.py
- wake_t/beamline_elements/field_element.py
- wake_t/beamline_elements/plasma_stage.py
Implement new base `FieldElement` class for all beamline elements where the particle beams are tracked in external fields (as opposed to `TMElement`, where the tracking is performed with transfer matrices).
As a result, the `PlasmaStage` and all it's subclasses are now also `FieldElement`s.
> Field element

- setup.cfg
- tests/test_openpmd_viewer.py
Add a unit test to check that the data generated with Wake-T can be read and analyzed with the openPMD viewer. In the past there have been issues with the output (#55) that should hopefully by detected with this test, should they return.
> Add openPMD viewer test

- tests/test_laser_initialization.py
- wake_t/diagnostics/openpmd_diag.py
- wake_t/fields/rz_wakefield.py
- wake_t/physics_models/laser/laser_pulse.py
- wake_t/physics_models/plasma_wakefields/qs_cold_fluid_1x3p.py
- wake_t/physics_models/plasma_wakefields/qs_rz_baxevanis/wakefield.py
- wake_t/utilities/other.py
Fixes a bug in the laser envelope amplitude, which would be divided by `sqrt(2)` in the case of linear polarization. The simulation results were correct, but the factor `sqrt(2)` should only be applied to the ponderomotive force, not the envelope amplitude itself. The only issue affecting the user was that the envelope amplitude in the diagnostics was `1/sqrt(2)` of the expected one.
Fixes #106.
> Fix laser envelope amplitude

- setup.cfg
We use semver and use major versions for potentially breaking changes. Practically, we only break the Python API very slightly every 2-3 years.
Thus, removing upper version contrain for better maintainability and following best practice.
> openPMD-api: No Upper Limit

- wake_t/beamline_elements/plasma_ramp.py
Density profiles given to a plasma ramp now need to include the input parameters `decay_length`, `density_top`, `density_down` and `position_down`. This makes them consistent with the predefined profiles included by default.
> Change input parameters of ramp profiles

- wake_t/physics_models/laser/laser_pulse.py
This PR allows the time step of the laser envelope solver to change. When a change is detected, the non-centered version of the solver is used for computing the next step.
> Allow laser envelope time step to change

- setup.cfg
There seems to be an issue with the latest numba release (0.57) where the output of `np.angle` seems to be `complex128`. This prevents the laser envelope solver from compiling.
This PR prevents Wake-T from installing numba 0.57 until we find a more appropriate solution.
> Avoid using latest numba release

- wake_t/__init__.py
- wake_t/utilities/numba.py
> Raise `RuntimeError` for numba 0.57.0

- .github/workflows/publish-to-pypi.yml
The action to publish to PyPI was outdated and no longer working. This PR updates it to use `actions/setup-python@v4` as well trusted publishing in PyPI.
> Update PyPI action

- docs/source/api/laser/laser_pulses/index.rst
- wake_t/fields/rz_wakefield.py
- wake_t/physics_models/laser/laser_pulse.py
This PR implements the possibility of reading a laser pulse from an openPMD file using the `lasy` library. In addition, the laser diagnostics of a Wake-T simulation now include the full complex envelope `a`.
> Implement `lasy` reader

- tests/test_field_element.py
- wake_t/beamline_elements/active_plasma_lens.py
- wake_t/beamline_elements/field_element.py
- wake_t/beamline_elements/plasma_ramp.py
- wake_t/beamline_elements/plasma_stage.py
Although in principle it is possible to pass a list of values to `dt_bunch`  (one value per bunch), this functionality was not documented nor functional. This PR fixes this issue.
> Fix bug when passing a list to `dt_bunch`

- .github/workflows/test-package.yml
- .readthedocs.yaml
- docs/source/getting_started/installation.rst
- setup.cfg
- wake_t/__init__.py
This PR removes support for Python 3.7. The supported (and tested) versions are now from 3.8 to ~3.12~ 3.11 (3.12 not yet supported by Numba https://github.com/numba/numba/issues/9197).
> Require Python `>=3.8` and update tests

- tests/test_active_plasma_lens.py
- tests/test_field_element.py
- tests/test_fluid_model.py
- tests/test_multibunch.py
- tests/test_ramps.py
- wake_t/beamline_elements/active_plasma_lens.py
- wake_t/beamline_elements/field_element.py
- wake_t/beamline_elements/plasma_ramp.py
- wake_t/beamline_elements/plasma_stage.py
- wake_t/fields/analytical_field.py
- wake_t/fields/gather.py
- wake_t/particles/deposition.py
- wake_t/particles/interpolation.py
- wake_t/particles/particle_bunch.py
- wake_t/particles/push/boris_pusher.py
- wake_t/particles/push/runge_kutta_4.py
- wake_t/physics_models/em_fields/linear_b_theta.py
- wake_t/physics_models/plasma_wakefields/custom_blowout.py
- wake_t/physics_models/plasma_wakefields/focusing_blowout.py
- wake_t/physics_models/plasma_wakefields/simple_blowout.py
- wake_t/tracking/tracker.py
- wake_t/utilities/numba.py
- Make `'boris'` the default pusher for the particle bunches.
- Raise a `ValueError` if the given `bunch_pusher` is not recognized.
- Faster particle gathering thanks to a more efficient method for resetting field arrays.
- Enable bunch pusher, bunch field gathering and analytical fields to run in parallel (other functions like those for bunch deposition are still serial. This will be gradually implemented).
- Define a new environment variable `'WAKET_NUM_THREADS'` that controls the number of parallel threads (by default, 1).
> Make `boris` the default bunch pusher and enable parallelism

- wake_t/physics_models/laser/envelope_solver.py
- wake_t/physics_models/laser/envelope_solver_non_centered.py
- wake_t/physics_models/laser/utils.py
This PR implements proper unwrapping (in 1D, on axis) of the complex envelope phase in the laser envelope solver. This improves the stability of the solver compared to the previous method. Since `np.unwrap` does not work with numba, a copy of the function that can be compiled with numba has been implemented.
> Implement 1D unwrapping of laser envelope phase

- tests/test_active_plasma_lens.py
- tests/test_custom_blowout.py
- tests/test_fluid_model.py
- tests/test_multibunch.py
- tests/test_ramps.py
- tests/test_simple_blowout.py
- wake_t/beamline_elements/field_element.py
- wake_t/tracking/tracker.py
This PR adds a new option (set to `True` by default) to push the bunches before saving them to the diagnostics.
Since the time step of the diagnostics can be different from that of the bunches, it could happen that the bunches appear in the diagnostics as they were at the last push, but not at the actual time of the diagnostics. Setting this parameter to ``True`` (default) ensures that an additional push is given to all bunches to evolve them to the diagnostics time before saving. This additional push will always have a time step smaller than the the time step of the bunch, so it has no detrimental impact on the accuracy of the simulation. However, it could make convergence studies more difficult to interpret, since the number of pushes will depend on `n_diags`. Therefore, it is exposed …
> Push bunches before saving to diagnostics

- tests/test_beamline.py
- tests/test_field_element.py
- tutorials/00_basic_tutorial.py
- tutorials/01_single_plasma_simulation.py
- wake_t/beamline_elements/tm_elements.py
- wake_t/particles/particle_bunch.py
- wake_t/tracking/tracker.py
Implement a built-in method to efficiently copy a `ParticleBunch`.
> Implement `ParticleBunch.copy`

- wake_t/beamline_elements/active_plasma_lens.py
- wake_t/beamline_elements/beamline.py
- wake_t/beamline_elements/field_element.py
- wake_t/beamline_elements/plasma_ramp.py
- wake_t/beamline_elements/plasma_stage.py
- wake_t/beamline_elements/tm_elements.py
- wake_t/tracking/progress_bar.py
- wake_t/tracking/tracker.py
Addresses #152 .
It also moves the `push_bunches_before_diags` option to the `__init__`, since this is a specific setting for `FieldElement` that is not needed for `TMElement`s. I noticed this when adding the `show_progress_bar` option to `Beamline.track`.
> Make progress bar optional
